channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=21.2.4
- pip:
  - mlflow==2.22.0
  - mypy-extensions==0.4.3
  - numpy==1.21.5
  - opentelemetry-exporter-otlp==1.35.0
  - pandas==1.4.2
  - psutil==7.0.0
  - scikit-learn==1.0.2
  - scipy==1.7.3
  - xgboost==1.4.0
name: mlflow-env
